language: c
sudo: required
branches:
  only:
    - develop
    - zfs-0.7-release
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
    - /^v\d+\.\d+(\.\S*)?$/
env:
  global:
    # Travis limits maximum log size, we have to cut tests output
    - CODECOV_TOKEN="987cf0f1-ae3b-477e-b645-954e682f99ec"
    - ZFS_TEST_TRAVIS_LOG_MAX_LENGTH=800

jobs:
  include:
    - os: linux
      arch: amd64
      env:
        - ZFS_BUILD_TAGS=1
        - RUN_UZFS_TESTS=1
        - RUN_ZTESTS=0
        - RELEASE_TAG_DOWNSTREAM=1
    - os: linux
      arch: amd64
      env:
        - ZFS_BUILD_TAGS=0
        - RUN_UZFS_TESTS=0
        - RUN_ZTESTS=1
        - RELEASE_TAG_DOWNSTREAM=0
before_install:
    - buildscripts/install-tool-dep.sh
install:
    - buildscripts/install-build-dep.sh
before_script:
    - make cstyle;
script:
    # run ztest and test supported zio backends
    - if [ $RUN_UZFS_TESTS = 1 ]; then
        export FIO_SRCDIR=$PWD/../fio;
        sudo bash ./print_debug_info.sh &
        sudo bash ../libcstor/tests/cstor/script/test_uzfs.sh -T all || travis_terminate 1;
      fi
    - if [ $RUN_ZTESTS = 1 ]; then
        sudo /sbin/modprobe zfs;
        travis_wait 10 /sbin/ztest || travis_terminate 1;
      fi

    # If this build is running due to travis release tag, and
    # this job indicates to push the release downstream, then
    # go ahead and tag the dependent repo.
    # Note that ZFS_BUILD_TAGs is enabled for `arm` and `amd`, 
    # but, release on downstream repository is triggered 
    # after `amd` images have been created. This is controlled
    # by ENV RELEASE_TAG_DOWNSTREAM.
    #
    # $TRAVIS_BRANCH contains the same value as $TRAVIS_TAG.
    # Example: v1.9.0-RC1 tag and v1.9.0-RC1 branch,
    # when github release tag is v1.9.0-RC1
    #
    # OpenEBS release are triggered from release branches that are named
    # as v1.9.x or v1.9.x-hotfix or v1.9.x-custom
    #
    # The tag to release branch conversion should be handled as follows:
    # v1.9.0-RC1 => should be v1.9.x
    # v1.9.0-hotfixid => should be v1.9.x-hotfixid
    # v1.9.0 => should be v1.9.x
    # v1.9.1 => should be v1.9.x
    # v1.9.0-custom-RC1 => should be v1.9.x-custom
    # v1.9.0-custom => should be v1.9.x-custom
    # v1.9.1-custom => should be v1.9.x-custom
    # Convert the TRAVIS_TAG to the corresponding release branch.
    # OpenEBS release are done from branches named as v1.9.x. 
    # Convert the TRAVIS_TAG to the corresponding release branch.
    #
    # Allow for building forked openebs pipelines. 
    # Tag the downstream repos under current repo org. 
    - if [ -z $REPO_ORG ]; then
        REPO_ORG=$(echo "$TRAVIS_REPO_SLUG" | cut -d'/' -f1);
        export REPO_ORG;
      fi
    - if [ ! -z $TRAVIS_TAG ] && [ $RELEASE_TAG_DOWNSTREAM = 1 ] && [ "$TRAVIS_REPO_SLUG" == "$REPO_ORG/cstor" ]; then
        TAG_SUFFIX=$(echo "$TRAVIS_TAG" | cut -d'-' -f2);
        if [ "$TAG_SUFFIX" == "$TRAVIS_TAG" ] || [[ $TAG_SUFFIX =~ ^RC ]]; then
          REL_SUFFIX="";
        else
          REL_SUFFIX="-$TAG_SUFFIX";
        fi

        REL_BRANCH=$(echo $(echo "$TRAVIS_TAG" | cut -d'-' -f1 | rev | cut -d'.' -f2- | rev).x$REL_SUFFIX);

        ./buildscripts/git-release "$REPO_ORG/libcstor" "$TRAVIS_TAG" "$REL_BRANCH" || travis_terminate 1;
      fi
after_failure:
    - find /var/tmp/test_results/current/log -type f -name '*' -printf "%f\n" -exec cut -c -$ZFS_TEST_TRAVIS_LOG_MAX_LENGTH {} \;
after_success:
    - find /var/tmp/test_results/current/log -type f -name '*' -printf "%f\n" -exec cut -c -$ZFS_TEST_TRAVIS_LOG_MAX_LENGTH {} \;
notifications:
  email:
    recipients:
    - ashutosh.kumar@mayadata.io
    - kiran.mova@mayadata.io
    - mayank.patel@mayadata.io
    - prateek.pandey@mayadata.io
    - shubham.bajpai@mayadata.io
