name: build

on: ['push']

jobs:

  cstor:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        uzfs_build: [0, 1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Branch
        run: |
          BRANCH="${GITHUB_REF##*/}"
          REPO_ORG=${{ github.repository_owner }}
          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
          echo "REPO_ORG=${REPO}" >> $GITHUB_ENV

      - name: Install Tool dependencies
        run: buildscripts/install-tool-dep.sh

      - name: Install Build dependencies
        run: UZFS_BUILD=${{ matrix.uzfs_build }} buildscipts/install-build-dep.sh

      - name: Check style
        run: make cstyle

      - name: Run Tests
        run: |
          if [ "${{ matrix.uzfs_build }}" = 1 ]; then
            export FIO_SRCDIR=$PWD/../fio
            sudo bash ./print_debug_info.sh &
            sudo bash ../libcstor/tests/cstor/script/test_uzfs.sh -T all || exit 1
          else
            sudo /sbin/modprobe zfs
            travis_wait 10 /sbin/ztest || exit 1
          fi